import { useEffect, useState, type FormEvent } from 'react'
import { Crown, MailPlus } from 'lucide-react'
import { useAuth } from '../components/AuthProvider'
import { Card, EmptyState, LoadingState, PageContainer } from '../components/ui'
import { getManagers, inviteManager } from '../services/api'
import type { StaffMember } from '../types/auth'

export function ManagerManagementPage() {
  const { session } = useAuth(); const [managers, setManagers] = useState<StaffMember[] | null>(null); const [error, setError] = useState(''); const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [sending, setSending] = useState(false)
  useEffect(() => { if (!session) return; getManagers(session.access_token).then(setManagers).catch(err => setError(err instanceof Error ? err.message : 'Could not load managers')) }, [session])
  async function submit(event: FormEvent) { event.preventDefault(); if (!session) return; setSending(true); setMessage(''); setError(''); try { const result = await inviteManager(session.access_token, fullName, email); setMessage(result.message); setFullName(''); setEmail('') } catch (err) { setError(err instanceof Error ? err.message : 'Could not invite manager') } finally { setSending(false) } }
  return <PageContainer><div className="page-heading"><p className="eyebrow">Manager administration</p><h1>Manager Management</h1><p>Invite trusted managers and review authorised leadership accounts.</p></div><div className="staff-grid"><Card><div className="section-heading"><div><p className="eyebrow">Invite new manager</p><h2>Add a manager</h2></div><MailPlus color="#B77466" /></div><form className="staff-form" onSubmit={submit}><label>Full name<input required value={fullName} onChange={e => setFullName(e.target.value)} /></label><label>Email address<input required type="email" value={email} onChange={e => setEmail(e.target.value)} /></label>{message && <p className="form-success" role="status">{message}</p>}{error && <p className="form-error" role="alert">{error}</p>}<button className="button" disabled={sending}>{sending ? 'Sending…' : 'Send Manager Invitation'}</button></form></Card><Card className="staff-list"><div className="section-heading"><div><p className="eyebrow">Authorised managers</p><h2>Manager accounts</h2></div><Crown color="#B77466" /></div>{error && !managers ? <p className="form-error">{error}</p> : managers === null ? <LoadingState label="Loading manager accounts…" /> : managers.length === 0 ? <EmptyState title="No managers found" detail="The initial manager setup may not have been completed." /> : <div className="member-list">{managers.map(manager => <article className="member" key={manager.id}><div><strong>{manager.full_name || 'Unnamed manager'}</strong><p>{manager.email}</p></div><div><span className="role-tag manager">Manager</span><small>{manager.is_active ? 'Active' : 'Inactive'} · {new Date(manager.created_at).toLocaleDateString()}</small></div></article>)}</div>}</Card></div></PageContainer>
}
