import { useEffect, useState, type FormEvent } from 'react'
import { MailPlus, Users } from 'lucide-react'
import { useAuth } from '../components/AuthProvider'
import { Card, EmptyState, LoadingState, PageContainer } from '../components/ui'
import { getStaff, inviteStaff } from '../services/api'
import type { StaffMember } from '../types/auth'
export function StaffManagementPage() { const { session } = useAuth(); const [staff, setStaff] = useState<StaffMember[] | null>(null); const [error, setError] = useState(''); const [fullName, setFullName] = useState(''); const [email, setEmail] = useState(''); const [message, setMessage] = useState(''); const [sending, setSending] = useState(false)
  useEffect(() => { if (!session) return; getStaff(session.access_token).then(setStaff).catch(err => setError(err instanceof Error ? err.message : 'Could not load staff')) }, [session])
  async function submit(event: FormEvent) { event.preventDefault(); if (!session) return; setSending(true); setMessage(''); setError(''); try { const result = await inviteStaff(session.access_token, fullName, email); setMessage(result.message); setFullName(''); setEmail('') } catch (err) { setError(err instanceof Error ? err.message : 'Could not invite staff') } finally { setSending(false) } }
  return <PageContainer><div className="page-heading"><p className="eyebrow">Manager administration</p><h1>Staff Management</h1><p>Invite staff securely and review authorised mall accounts.</p></div><div className="staff-grid"><Card><div className="section-heading"><div><p className="eyebrow">Invite staff</p><h2>Add a team member</h2></div><MailPlus color="#B77466" /></div><form className="staff-form" onSubmit={submit}><label>Full name<input required value={fullName} onChange={e => setFullName(e.target.value)} /></label><label>Email address<input required type="email" value={email} onChange={e => setEmail(e.target.value)} /></label>{message && <p className="form-success" role="status">{message}</p>}{error && <p className="form-error" role="alert">{error}</p>}<button className="button" disabled={sending}>{sending ? 'Sending…' : 'Send staff invitation'}</button></form></Card><Card className="staff-list"><div className="section-heading"><div><p className="eyebrow">Authorised users</p><h2>Accounts</h2></div><Users color="#B77466" /></div>{error && !staff ? <p className="form-error">{error}</p> : staff === null ? <LoadingState label="Loading staff accounts…" /> : staff.length === 0 ? <EmptyState title="No accounts yet" detail="Invite a staff member to get started." /> : <div className="member-list">{staff.map(member => <article className="member" key={member.id}><div><strong>{member.full_name || 'Unnamed user'}</strong><p>{member.email}</p></div><div><span className={`role-tag ${member.role}`}>{member.role}</span><small>{member.is_active ? 'Active' : 'Inactive'} · {new Date(member.created_at).toLocaleDateString()}</small></div></article>)}</div>}</Card></div></PageContainer> }
