import { useEffect, useMemo, useState, type FormEvent } from 'react'
import { PackagePlus, ReceiptText, Wrench } from 'lucide-react'
import { useAuth } from '../components/AuthProvider'
import { Card, LoadingState, PageContainer } from '../components/ui'
import { getProducts, getSuppliers, recordStock, type Product, type Supplier } from '../services/api'
type Mode = 'STOCK_IN' | 'SALE' | 'DAMAGE'
const labels: Record<Mode, string> = { STOCK_IN: 'Stock In', SALE: 'Sale', DAMAGE: 'Damage' }
export function StockOperationsFixed() {
  const { session } = useAuth(); const accessToken = session?.access_token ?? ''; const [mode, setMode] = useState<Mode>('STOCK_IN'); const [products, setProducts] = useState<Product[]>([]); const [suppliers, setSuppliers] = useState<Supplier[]>([]); const [loading, setLoading] = useState(true); const [productId, setProductId] = useState(''); const [query, setQuery] = useState(''); const [quantity, setQuantity] = useState(''); const [supplierId, setSupplierId] = useState(''); const [note, setNote] = useState(''); const [error, setError] = useState(''); const [success, setSuccess] = useState(''); const [saving, setSaving] = useState(false)
  const selected = products.find(product => product.id === productId); const filtered = useMemo(() => products.filter(product => `${product.name} ${product.sku} ${product.barcode || ''}`.toLowerCase().includes(query.toLowerCase())).slice(0, 8), [products, query])
  const load = async () => { if (!accessToken) { setLoading(false); return }; setLoading(true); setError(''); const [productResult, supplierResult] = await Promise.allSettled([getProducts(accessToken), getSuppliers(accessToken)]); if (productResult.status === 'fulfilled') setProducts(productResult.value); else setError(productResult.reason instanceof Error ? productResult.reason.message : 'Unable to load products.'); if (supplierResult.status === 'fulfilled') setSuppliers(supplierResult.value); else setError(previous => previous || (supplierResult.reason instanceof Error ? supplierResult.reason.message : 'Unable to load suppliers.')); setLoading(false) }
  useEffect(() => { void load() }, [accessToken]); const amount = Number(quantity) || 0; const next = selected ? mode === 'STOCK_IN' ? selected.current_stock + amount : selected.current_stock - amount : 0
  async function submit(event: FormEvent) { event.preventDefault(); if (!accessToken || !selected) return; setSaving(true); setError(''); setSuccess(''); try { const result = await recordStock(accessToken, { product_id: selected.id, operation_type: mode, quantity: amount, supplier_id: mode === 'STOCK_IN' ? supplierId || null : null, note: note || null }); setSuccess(`Stock updated successfully. ${selected.name}: ${result.stock_before} → ${result.stock_after}`); setQuantity(''); setNote(''); void load() } catch (err) { setError(err instanceof Error ? err.message : 'Could not update stock') } finally { setSaving(false) } }
  return <PageContainer><div className="page-heading"><p className="eyebrow">Live inventory</p><h1>Stock Operations</h1><p>Every update is securely recorded in stock history.</p></div>{loading ? <LoadingState label="Loading products and suppliers…" /> : <><div className="operation-tabs">{(['STOCK_IN', 'SALE', 'DAMAGE'] as Mode[]).map(item => <button type="button" className={mode === item ? 'selected' : ''} onClick={() => setMode(item)} key={item}>{item === 'STOCK_IN' ? <PackagePlus /> : item === 'SALE' ? <ReceiptText /> : <Wrench />}{labels[item]}</button>)}</div><Card><form className="stock-form" onSubmit={submit}><label>Find product<input value={query} onChange={event => setQuery(event.target.value)} placeholder="Name, SKU or barcode" /></label>{query && <div className="product-options">{filtered.map(product => <button type="button" key={product.id} onClick={() => { setProductId(product.id); setQuery(product.name) }}><strong>{product.name}</strong><small>{product.sku} · {product.current_stock} {product.unit}</small></button>)}{filtered.length === 0 && <p>No matching active products found.</p>}</div>}{selected && <div className="selected-product"><strong>{selected.name}</strong><span>{selected.sku} · Current stock: <b>{selected.current_stock} {selected.unit}</b></span></div>}<label>{mode === 'STOCK_IN' ? 'Quantity received' : mode === 'SALE' ? 'Quantity sold' : 'Damaged quantity'}<input required min="0.001" step="0.001" type="number" value={quantity} onChange={event => setQuantity(event.target.value)} /></label>{mode === 'STOCK_IN' && <label>Supplier<select value={supplierId} onChange={event => setSupplierId(event.target.value)}><option value="">No supplier selected</option>{suppliers.filter(supplier => supplier.is_active).map(supplier => <option value={supplier.id} key={supplier.id}>{supplier.name}</option>)}</select></label>}<label>{mode === 'DAMAGE' ? 'Reason' : 'Reference / note'}<input required={mode === 'DAMAGE'} value={note} onChange={event => setNote(event.target.value)} /></label>{selected && amount > 0 && <div className="stock-preview">Current: {selected.current_stock} {mode === 'STOCK_IN' ? '+' : '−'} {amount} = <strong>{next}</strong></div>}{error && <p className="form-error" role="alert">{error}</p>}{success && <p className="form-success" role="status">{success}</p>}<button className="button" disabled={!selected || amount <= 0 || saving}>{saving ? 'Recording…' : `Record ${labels[mode]}`}</button></form></Card></>}</PageContainer>
}
